using Aspire.Hosting;
using Aspire.Hosting.ApplicationModel;

namespace RVR.Framework.Aspire;

/// <summary>
/// Extension methods for configuring RIVORA Framework resources in a .NET Aspire distributed application.
/// </summary>
public static class RivoraDistributedApplicationExtensions
{
    /// <summary>
    /// Adds a SQL Server resource configured for the RIVORA Framework with a default "RVRFrameworkDb" database.
    /// </summary>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name for the SQL Server instance.</param>
    /// <returns>A resource builder for the SQL Server resource.</returns>
    public static IResourceBuilder<SqlServerServerResource> AddRivoraSqlServer(
        this IDistributedApplicationBuilder builder,
        string name = "sql")
    {
        var sqlServer = builder.AddSqlServer(name)
            .WithLifetime(ContainerLifetime.Persistent);

        return sqlServer;
    }

    /// <summary>
    /// Adds a PostgreSQL resource configured for the RIVORA Framework with a default "RVRFrameworkDb" database.
    /// </summary>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name for the PostgreSQL instance.</param>
    /// <returns>A resource builder for the PostgreSQL resource.</returns>
    public static IResourceBuilder<PostgresServerResource> AddRivoraPostgres(
        this IDistributedApplicationBuilder builder,
        string name = "postgres")
    {
        var postgres = builder.AddPostgres(name)
            .WithLifetime(ContainerLifetime.Persistent)
            .WithPgAdmin();

        return postgres;
    }

    /// <summary>
    /// Adds a Redis resource for RIVORA Framework caching.
    /// </summary>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name for the Redis instance.</param>
    /// <returns>A resource builder for the Redis resource.</returns>
    public static IResourceBuilder<RedisResource> AddRivoraRedis(
        this IDistributedApplicationBuilder builder,
        string name = "cache")
    {
        var redis = builder.AddRedis(name)
            .WithLifetime(ContainerLifetime.Persistent)
            .WithRedisInsight();

        return redis;
    }

    /// <summary>
    /// Adds a RabbitMQ resource for RIVORA Framework messaging.
    /// </summary>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name for the RabbitMQ instance.</param>
    /// <returns>A resource builder for the RabbitMQ resource.</returns>
    public static IResourceBuilder<RabbitMQServerResource> AddRivoraRabbitMQ(
        this IDistributedApplicationBuilder builder,
        string name = "messaging")
    {
        var rabbitmq = builder.AddRabbitMQ(name)
            .WithLifetime(ContainerLifetime.Persistent)
            .WithManagementPlugin();

        return rabbitmq;
    }

    /// <summary>
    /// Adds a RIVORA project resource with external HTTP endpoints.
    /// Use this with project types generated by the AppHost (e.g., Projects.RVR_Framework_Api).
    /// </summary>
    /// <typeparam name="TProject">The Aspire project resource type.</typeparam>
    /// <param name="builder">The distributed application builder.</param>
    /// <param name="name">The resource name for the project.</param>
    /// <returns>A resource builder for the project resource.</returns>
    public static IResourceBuilder<ProjectResource> AddRivoraProject<TProject>(
        this IDistributedApplicationBuilder builder,
        string name)
        where TProject : IProjectMetadata, new()
    {
        return builder.AddProject<TProject>(name)
            .WithExternalHttpEndpoints();
    }
}
