using Spectre.Console;
using System.Diagnostics;
using System.Text;

namespace RVR.CLI.Commands;

/// <summary>
/// Provides load testing functionality using k6.
/// </summary>
public static class BenchmarkCommand
{
    /// <summary>
    /// Executes the benchmark command to run load tests.
    /// </summary>
    /// <param name="url">Target URL to test.</param>
    /// <param name="duration">Test duration (e.g., 30s, 5m).</param>
    /// <param name="vus">Number of virtual users.</param>
    /// <param name="output">Output format (json, html, console).</param>
    /// <param name="scenario">Test scenario (smoke, load, stress).</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    public static async Task ExecuteAsync(
        string url,
        string duration,
        int vus,
        string output,
        string scenario)
    {
        AnsiConsole.Write(new FigletText("Benchmark").Color(Color.Cyan1));
        AnsiConsole.MarkupLine("[grey]Load testing with k6[/]" + Environment.NewLine);

        // Validate k6 installation
        if (!IsK6Installed())
        {
            AnsiConsole.MarkupLine("[bold red]Error:[/] k6 is not installed.");
            AnsiConsole.MarkupLine("[yellow]Install k6:[/]");
            AnsiConsole.MarkupLine("  macOS: [cyan]brew install k6[/]");
            AnsiConsole.MarkupLine("  Linux: [cyan]sudo apt install k6[/]");
            AnsiConsole.MarkupLine("  Windows: [cyan]choco install k6[/]");
            return;
        }

        var config = GetScenarioConfig(scenario, duration, vus);

        var configTable = new Table();
        configTable.AddColumn("Setting");
        configTable.AddColumn("Value");
        configTable.AddRow("[cyan]Target URL[/]", url);
        configTable.AddRow("[cyan]Scenario[/]", scenario);
        configTable.AddRow("[cyan]Duration[/]", config.Duration);
        configTable.AddRow("[cyan]Virtual Users[/]", config.Vus.ToString());
        configTable.AddRow("[cyan]Output Format[/]", output);
        AnsiConsole.Write(configTable);
        AnsiConsole.WriteLine();

        // Generate k6 script
        var scriptPath = GenerateK6Script(url, config);
        AnsiConsole.MarkupLine($"[green]✓ Generated k6 script:[/] {scriptPath}");
        AnsiConsole.WriteLine();

        // Run benchmark
        await RunBenchmark(scriptPath, output);

        await Task.CompletedTask;
    }

    private static bool IsK6Installed()
    {
        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = "k6",
                Arguments = "version",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };
            using var process = Process.Start(psi);
            process?.WaitForExit();
            return process?.ExitCode == 0;
        }
        catch
        {
            return false;
        }
    }

    private static (string Duration, int Vus, string Description) GetScenarioConfig(string scenario, string duration, int vus)
    {
        return scenario.ToLower() switch
        {
            "smoke" => ("1m", 5, "Quick smoke test with minimal load"),
            "load" => (duration, vus, "Standard load test"),
            "stress" => ("5m", vus * 3, "Stress test with high load"),
            "spike" => ("3m", vus * 5, "Spike test with sudden traffic increase"),
            "soak" => ("30m", vus, "Soak test for memory leaks"),
            _ => (duration, vus, "Custom scenario")
        };
    }

    private static string GenerateK6Script(string url, (string Duration, int Vus, string Description) config)
    {
        var scriptPath = Path.Combine(Path.GetTempPath(), $"k6_benchmark_{Guid.NewGuid()}.js");

        var script = $@"// RIVORA Framework Load Test Script
// Generated by rvr benchmark command
// Scenario: {config.Description}

import http from 'k6/http';
import {{ check, sleep }} from 'k6';
import {{ htmlReport }} from 'https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js';
import {{ textSummary }} from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';

export const options = {{
  scenarios: {{
    load_test: {{
      executor: 'constant-vus',
      vus: {config.Vus},
      duration: '{config.Duration}',
      gracefulStop: '30s',
    }},
  }},
  thresholds: {{
    http_req_duration: ['p(95)<500'], // 95% of requests should complete within 500ms
    http_req_failed: ['rate<0.01'], // Error rate should be less than 1%
    http_reqs: ['rate>100'], // At least 100 requests per second
  }},
}};

const BASE_URL = '{url.TrimEnd('/')}';
const HEADERS = {{
  'Content-Type': 'application/json',
  'User-Agent': 'RVR-Framework-Benchmark/1.0',
}};

export default function () {{
  // Health check
  let response = http.get(`${{BASE_URL}}/health`, {{ headers: HEADERS }});
  check(response, {{
    'health check status is 200': (r) => r.status === 200,
    'health check duration OK': (r) => r.timings.duration < 100,
  }});
  sleep(0.5);

  // API endpoint test (adjust based on your API)
  response = http.get(`${{BASE_URL}}/api`, {{ headers: HEADERS }});
  check(response, {{
    'api status is 200 or 404': (r) => [200, 404].includes(r.status),
  }});
  sleep(0.5);
}}

export function handleSummary(data) {{
  return {{
    'stdout': textSummary(data, {{ indent: ' ', enableColors: true }}),
  }};
}}
";
        File.WriteAllText(scriptPath, script);
        return scriptPath;
    }

    private static async Task RunBenchmark(string scriptPath, string outputFormat)
    {
        AnsiConsole.MarkupLine("[bold blue]Starting load test...[/]" + Environment.NewLine);

        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = "k6",
                Arguments = $"run {scriptPath}",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = new Process { StartInfo = psi };

            var outputBuilder = new StringBuilder();
            var errorBuilder = new StringBuilder();

            process.OutputDataReceived += (s, e) =>
            {
                if (!string.IsNullOrEmpty(e.Data))
                {
                    outputBuilder.AppendLine(e.Data);
                    AnsiConsole.MarkupLine($"[grey]{e.Data}[/]");
                }
            };

            process.ErrorDataReceived += (s, e) =>
            {
                if (!string.IsNullOrEmpty(e.Data))
                {
                    errorBuilder.AppendLine(e.Data);
                    AnsiConsole.MarkupLine($"[red]{e.Data}[/]");
                }
            };

            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();

            await Task.Run(() =>
            {
                process.WaitForExit();
            });

            AnsiConsole.WriteLine();

            if (process.ExitCode == 0)
            {
                AnsiConsole.MarkupLine("[bold green]✓ Load test completed successfully![/]");
            }
            else
            {
                AnsiConsole.MarkupLine($"[bold red]✗ Load test failed with exit code {process.ExitCode}[/]");
            }

            // Display summary
            DisplaySummary(outputBuilder.ToString());
        }
        catch (Exception ex)
        {
            AnsiConsole.MarkupLine($"[bold red]Error running benchmark:[/] {ex.Message}");
        }
        finally
        {
            // Cleanup
            if (File.Exists(scriptPath))
            {
                File.Delete(scriptPath);
            }
        }
    }

    private static void DisplaySummary(string output)
    {
        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine("[bold]Test Summary:[/]" + Environment.NewLine);

        // Parse and display key metrics
        var lines = output.Split('\n');
        var metrics = new List<(string Name, string Value)>();

        foreach (var line in lines)
        {
            if (line.Contains("http_req_duration"))
            {
                var parts = line.Split(new[] { ':' }, 2);
                if (parts.Length == 2)
                {
                    metrics.Add(("HTTP Request Duration", parts[1].Trim()));
                }
            }
            else if (line.Contains("http_reqs"))
            {
                var parts = line.Split(new[] { ':' }, 2);
                if (parts.Length == 2)
                {
                    metrics.Add(("HTTP Requests/sec", parts[1].Trim()));
                }
            }
            else if (line.Contains("data_received"))
            {
                var parts = line.Split(new[] { ':' }, 2);
                if (parts.Length == 2)
                {
                    metrics.Add(("Data Received", parts[1].Trim()));
                }
            }
        }

        if (metrics.Count > 0)
        {
            var table = new Table();
            table.AddColumn("Metric");
            table.AddColumn("Value");

            foreach (var (name, value) in metrics)
            {
                table.AddRow($"[cyan]{name}[/]", $"[white]{value}[/]");
            }

            AnsiConsole.Write(table);
        }

        AnsiConsole.WriteLine();
        AnsiConsole.MarkupLine("[yellow]Tip:[/] For detailed HTML report, run:");
        AnsiConsole.MarkupLine($"  [cyan]k6 run --out json=results.json {Path.GetFileName(Path.GetTempPath() + "k6_benchmark_*.js")}[/]");
    }
}
